// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"online-store/gen/models"
)

// NewPostV1LoginParams creates a new PostV1LoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1LoginParams() *PostV1LoginParams {
	return &PostV1LoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1LoginParamsWithTimeout creates a new PostV1LoginParams object
// with the ability to set a timeout on a request.
func NewPostV1LoginParamsWithTimeout(timeout time.Duration) *PostV1LoginParams {
	return &PostV1LoginParams{
		timeout: timeout,
	}
}

// NewPostV1LoginParamsWithContext creates a new PostV1LoginParams object
// with the ability to set a context for a request.
func NewPostV1LoginParamsWithContext(ctx context.Context) *PostV1LoginParams {
	return &PostV1LoginParams{
		Context: ctx,
	}
}

// NewPostV1LoginParamsWithHTTPClient creates a new PostV1LoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1LoginParamsWithHTTPClient(client *http.Client) *PostV1LoginParams {
	return &PostV1LoginParams{
		HTTPClient: client,
	}
}

/*
PostV1LoginParams contains all the parameters to send to the API endpoint

	for the post v1 login operation.

	Typically these are written to a http.Request.
*/
type PostV1LoginParams struct {

	/* Data.

	   login request data
	*/
	Data *models.LoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1LoginParams) WithDefaults() *PostV1LoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1LoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 login params
func (o *PostV1LoginParams) WithTimeout(timeout time.Duration) *PostV1LoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 login params
func (o *PostV1LoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 login params
func (o *PostV1LoginParams) WithContext(ctx context.Context) *PostV1LoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 login params
func (o *PostV1LoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 login params
func (o *PostV1LoginParams) WithHTTPClient(client *http.Client) *PostV1LoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 login params
func (o *PostV1LoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post v1 login params
func (o *PostV1LoginParams) WithData(data *models.LoginRequest) *PostV1LoginParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post v1 login params
func (o *PostV1LoginParams) SetData(data *models.LoginRequest) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1LoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
