// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"online-store/gen/models"
)

// NewPostV1ProductsParams creates a new PostV1ProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1ProductsParams() *PostV1ProductsParams {
	return &PostV1ProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1ProductsParamsWithTimeout creates a new PostV1ProductsParams object
// with the ability to set a timeout on a request.
func NewPostV1ProductsParamsWithTimeout(timeout time.Duration) *PostV1ProductsParams {
	return &PostV1ProductsParams{
		timeout: timeout,
	}
}

// NewPostV1ProductsParamsWithContext creates a new PostV1ProductsParams object
// with the ability to set a context for a request.
func NewPostV1ProductsParamsWithContext(ctx context.Context) *PostV1ProductsParams {
	return &PostV1ProductsParams{
		Context: ctx,
	}
}

// NewPostV1ProductsParamsWithHTTPClient creates a new PostV1ProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1ProductsParamsWithHTTPClient(client *http.Client) *PostV1ProductsParams {
	return &PostV1ProductsParams{
		HTTPClient: client,
	}
}

/*
PostV1ProductsParams contains all the parameters to send to the API endpoint

	for the post v1 products operation.

	Typically these are written to a http.Request.
*/
type PostV1ProductsParams struct {

	/* Data.

	   product request body
	*/
	Data *models.ProductData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ProductsParams) WithDefaults() *PostV1ProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1ProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 products params
func (o *PostV1ProductsParams) WithTimeout(timeout time.Duration) *PostV1ProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 products params
func (o *PostV1ProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 products params
func (o *PostV1ProductsParams) WithContext(ctx context.Context) *PostV1ProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 products params
func (o *PostV1ProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 products params
func (o *PostV1ProductsParams) WithHTTPClient(client *http.Client) *PostV1ProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 products params
func (o *PostV1ProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post v1 products params
func (o *PostV1ProductsParams) WithData(data *models.ProductData) *PostV1ProductsParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post v1 products params
func (o *PostV1ProductsParams) SetData(data *models.ProductData) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1ProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
