// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"online-store/gen/models"
)

// PostV1ProductsReader is a Reader for the PostV1Products structure.
type PostV1ProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1ProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1ProductsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostV1ProductsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostV1ProductsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostV1ProductsCreated creates a PostV1ProductsCreated with default headers values
func NewPostV1ProductsCreated() *PostV1ProductsCreated {
	return &PostV1ProductsCreated{}
}

/*
PostV1ProductsCreated describes a response with status code 201, with default header values.

success create new product
*/
type PostV1ProductsCreated struct {
	Payload *models.BaseResponse
}

// IsSuccess returns true when this post v1 products created response has a 2xx status code
func (o *PostV1ProductsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 products created response has a 3xx status code
func (o *PostV1ProductsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 products created response has a 4xx status code
func (o *PostV1ProductsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 products created response has a 5xx status code
func (o *PostV1ProductsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 products created response a status code equal to that given
func (o *PostV1ProductsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post v1 products created response
func (o *PostV1ProductsCreated) Code() int {
	return 201
}

func (o *PostV1ProductsCreated) Error() string {
	return fmt.Sprintf("[POST /v1/products][%d] postV1ProductsCreated  %+v", 201, o.Payload)
}

func (o *PostV1ProductsCreated) String() string {
	return fmt.Sprintf("[POST /v1/products][%d] postV1ProductsCreated  %+v", 201, o.Payload)
}

func (o *PostV1ProductsCreated) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *PostV1ProductsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ProductsUnauthorized creates a PostV1ProductsUnauthorized with default headers values
func NewPostV1ProductsUnauthorized() *PostV1ProductsUnauthorized {
	return &PostV1ProductsUnauthorized{}
}

/*
PostV1ProductsUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type PostV1ProductsUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post v1 products unauthorized response has a 2xx status code
func (o *PostV1ProductsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 products unauthorized response has a 3xx status code
func (o *PostV1ProductsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 products unauthorized response has a 4xx status code
func (o *PostV1ProductsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 products unauthorized response has a 5xx status code
func (o *PostV1ProductsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 products unauthorized response a status code equal to that given
func (o *PostV1ProductsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post v1 products unauthorized response
func (o *PostV1ProductsUnauthorized) Code() int {
	return 401
}

func (o *PostV1ProductsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/products][%d] postV1ProductsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1ProductsUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/products][%d] postV1ProductsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1ProductsUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostV1ProductsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ProductsDefault creates a PostV1ProductsDefault with default headers values
func NewPostV1ProductsDefault(code int) *PostV1ProductsDefault {
	return &PostV1ProductsDefault{
		_statusCode: code,
	}
}

/*
PostV1ProductsDefault describes a response with status code -1, with default header values.

error
*/
type PostV1ProductsDefault struct {
	_statusCode int

	Payload *models.BaseResponse
}

// IsSuccess returns true when this post v1 products default response has a 2xx status code
func (o *PostV1ProductsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post v1 products default response has a 3xx status code
func (o *PostV1ProductsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post v1 products default response has a 4xx status code
func (o *PostV1ProductsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post v1 products default response has a 5xx status code
func (o *PostV1ProductsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post v1 products default response a status code equal to that given
func (o *PostV1ProductsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post v1 products default response
func (o *PostV1ProductsDefault) Code() int {
	return o._statusCode
}

func (o *PostV1ProductsDefault) Error() string {
	return fmt.Sprintf("[POST /v1/products][%d] PostV1Products default  %+v", o._statusCode, o.Payload)
}

func (o *PostV1ProductsDefault) String() string {
	return fmt.Sprintf("[POST /v1/products][%d] PostV1Products default  %+v", o._statusCode, o.Payload)
}

func (o *PostV1ProductsDefault) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *PostV1ProductsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
