// Code generated by go-swagger; DO NOT EDIT.

package product

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new product API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for product API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV1Products(params *GetV1ProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1ProductsOK, error)

	PostV1Products(params *PostV1ProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1ProductsCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV1Products products list data

get product list data API
*/
func (a *Client) GetV1Products(params *GetV1ProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1ProductsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1ProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Products",
		Method:             "GET",
		PathPattern:        "/v1/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1ProductsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1ProductsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetV1ProductsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostV1Products creates new product

create new product API
*/
func (a *Client) PostV1Products(params *PostV1ProductsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1ProductsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1ProductsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostV1Products",
		Method:             "POST",
		PathPattern:        "/v1/products",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1ProductsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostV1ProductsCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostV1ProductsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
