// Code generated by go-swagger; DO NOT EDIT.

package history

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new history API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for history API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	PostV1Histories(params *PostV1HistoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1HistoriesCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
PostV1Histories creates new history

create new history API
*/
func (a *Client) PostV1Histories(params *PostV1HistoriesParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1HistoriesCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1HistoriesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostV1Histories",
		Method:             "POST",
		PathPattern:        "/v1/histories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1HistoriesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostV1HistoriesCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostV1HistoriesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
