// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new cart API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for cart API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV1Carts(params *GetV1CartsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1CartsOK, error)

	PostV1Carts(params *PostV1CartsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1CartsCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV1Carts carts list data

get carts list data API
*/
func (a *Client) GetV1Carts(params *GetV1CartsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1CartsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1CartsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Carts",
		Method:             "GET",
		PathPattern:        "/v1/carts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1CartsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1CartsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetV1CartsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostV1Carts creates new cart

create new cart API
*/
func (a *Client) PostV1Carts(params *PostV1CartsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostV1CartsCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1CartsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostV1Carts",
		Method:             "POST",
		PathPattern:        "/v1/carts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1CartsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostV1CartsCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostV1CartsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
