// Code generated by go-swagger; DO NOT EDIT.

package cart

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"online-store/gen/models"
)

// PostV1CartsReader is a Reader for the PostV1Carts structure.
type PostV1CartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1CartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostV1CartsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostV1CartsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPostV1CartsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostV1CartsCreated creates a PostV1CartsCreated with default headers values
func NewPostV1CartsCreated() *PostV1CartsCreated {
	return &PostV1CartsCreated{}
}

/*
PostV1CartsCreated describes a response with status code 201, with default header values.

success create new cart
*/
type PostV1CartsCreated struct {
	Payload *models.BaseResponse
}

// IsSuccess returns true when this post v1 carts created response has a 2xx status code
func (o *PostV1CartsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post v1 carts created response has a 3xx status code
func (o *PostV1CartsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 carts created response has a 4xx status code
func (o *PostV1CartsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post v1 carts created response has a 5xx status code
func (o *PostV1CartsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 carts created response a status code equal to that given
func (o *PostV1CartsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post v1 carts created response
func (o *PostV1CartsCreated) Code() int {
	return 201
}

func (o *PostV1CartsCreated) Error() string {
	return fmt.Sprintf("[POST /v1/carts][%d] postV1CartsCreated  %+v", 201, o.Payload)
}

func (o *PostV1CartsCreated) String() string {
	return fmt.Sprintf("[POST /v1/carts][%d] postV1CartsCreated  %+v", 201, o.Payload)
}

func (o *PostV1CartsCreated) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *PostV1CartsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1CartsUnauthorized creates a PostV1CartsUnauthorized with default headers values
func NewPostV1CartsUnauthorized() *PostV1CartsUnauthorized {
	return &PostV1CartsUnauthorized{}
}

/*
PostV1CartsUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type PostV1CartsUnauthorized struct {
	Payload interface{}
}

// IsSuccess returns true when this post v1 carts unauthorized response has a 2xx status code
func (o *PostV1CartsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post v1 carts unauthorized response has a 3xx status code
func (o *PostV1CartsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post v1 carts unauthorized response has a 4xx status code
func (o *PostV1CartsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post v1 carts unauthorized response has a 5xx status code
func (o *PostV1CartsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post v1 carts unauthorized response a status code equal to that given
func (o *PostV1CartsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post v1 carts unauthorized response
func (o *PostV1CartsUnauthorized) Code() int {
	return 401
}

func (o *PostV1CartsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/carts][%d] postV1CartsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1CartsUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/carts][%d] postV1CartsUnauthorized  %+v", 401, o.Payload)
}

func (o *PostV1CartsUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *PostV1CartsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1CartsDefault creates a PostV1CartsDefault with default headers values
func NewPostV1CartsDefault(code int) *PostV1CartsDefault {
	return &PostV1CartsDefault{
		_statusCode: code,
	}
}

/*
PostV1CartsDefault describes a response with status code -1, with default header values.

error
*/
type PostV1CartsDefault struct {
	_statusCode int

	Payload *models.BaseResponse
}

// IsSuccess returns true when this post v1 carts default response has a 2xx status code
func (o *PostV1CartsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this post v1 carts default response has a 3xx status code
func (o *PostV1CartsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this post v1 carts default response has a 4xx status code
func (o *PostV1CartsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this post v1 carts default response has a 5xx status code
func (o *PostV1CartsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this post v1 carts default response a status code equal to that given
func (o *PostV1CartsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the post v1 carts default response
func (o *PostV1CartsDefault) Code() int {
	return o._statusCode
}

func (o *PostV1CartsDefault) Error() string {
	return fmt.Sprintf("[POST /v1/carts][%d] PostV1Carts default  %+v", o._statusCode, o.Payload)
}

func (o *PostV1CartsDefault) String() string {
	return fmt.Sprintf("[POST /v1/carts][%d] PostV1Carts default  %+v", o._statusCode, o.Payload)
}

func (o *PostV1CartsDefault) GetPayload() *models.BaseResponse {
	return o.Payload
}

func (o *PostV1CartsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BaseResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
