// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetV1UserIDParams creates a new GetV1UserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1UserIDParams() *GetV1UserIDParams {
	return &GetV1UserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1UserIDParamsWithTimeout creates a new GetV1UserIDParams object
// with the ability to set a timeout on a request.
func NewGetV1UserIDParamsWithTimeout(timeout time.Duration) *GetV1UserIDParams {
	return &GetV1UserIDParams{
		timeout: timeout,
	}
}

// NewGetV1UserIDParamsWithContext creates a new GetV1UserIDParams object
// with the ability to set a context for a request.
func NewGetV1UserIDParamsWithContext(ctx context.Context) *GetV1UserIDParams {
	return &GetV1UserIDParams{
		Context: ctx,
	}
}

// NewGetV1UserIDParamsWithHTTPClient creates a new GetV1UserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1UserIDParamsWithHTTPClient(client *http.Client) *GetV1UserIDParams {
	return &GetV1UserIDParams{
		HTTPClient: client,
	}
}

/*
GetV1UserIDParams contains all the parameters to send to the API endpoint

	for the get v1 user ID operation.

	Typically these are written to a http.Request.
*/
type GetV1UserIDParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UserIDParams) WithDefaults() *GetV1UserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1UserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 user ID params
func (o *GetV1UserIDParams) WithTimeout(timeout time.Duration) *GetV1UserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 user ID params
func (o *GetV1UserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 user ID params
func (o *GetV1UserIDParams) WithContext(ctx context.Context) *GetV1UserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 user ID params
func (o *GetV1UserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 user ID params
func (o *GetV1UserIDParams) WithHTTPClient(client *http.Client) *GetV1UserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 user ID params
func (o *GetV1UserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get v1 user ID params
func (o *GetV1UserIDParams) WithID(id int64) *GetV1UserIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get v1 user ID params
func (o *GetV1UserIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1UserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
