// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"online-store/gen/models"
)

// NewPostV1UserParams creates a new PostV1UserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostV1UserParams() *PostV1UserParams {
	return &PostV1UserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostV1UserParamsWithTimeout creates a new PostV1UserParams object
// with the ability to set a timeout on a request.
func NewPostV1UserParamsWithTimeout(timeout time.Duration) *PostV1UserParams {
	return &PostV1UserParams{
		timeout: timeout,
	}
}

// NewPostV1UserParamsWithContext creates a new PostV1UserParams object
// with the ability to set a context for a request.
func NewPostV1UserParamsWithContext(ctx context.Context) *PostV1UserParams {
	return &PostV1UserParams{
		Context: ctx,
	}
}

// NewPostV1UserParamsWithHTTPClient creates a new PostV1UserParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostV1UserParamsWithHTTPClient(client *http.Client) *PostV1UserParams {
	return &PostV1UserParams{
		HTTPClient: client,
	}
}

/*
PostV1UserParams contains all the parameters to send to the API endpoint

	for the post v1 user operation.

	Typically these are written to a http.Request.
*/
type PostV1UserParams struct {

	// Data.
	Data *models.CreateUserRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post v1 user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1UserParams) WithDefaults() *PostV1UserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post v1 user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostV1UserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post v1 user params
func (o *PostV1UserParams) WithTimeout(timeout time.Duration) *PostV1UserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post v1 user params
func (o *PostV1UserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post v1 user params
func (o *PostV1UserParams) WithContext(ctx context.Context) *PostV1UserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post v1 user params
func (o *PostV1UserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post v1 user params
func (o *PostV1UserParams) WithHTTPClient(client *http.Client) *PostV1UserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post v1 user params
func (o *PostV1UserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post v1 user params
func (o *PostV1UserParams) WithData(data *models.CreateUserRequest) *PostV1UserParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post v1 user params
func (o *PostV1UserParams) SetData(data *models.CreateUserRequest) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PostV1UserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
