// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new user API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for user API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV1UserID(params *GetV1UserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UserIDOK, error)

	PostV1User(params *PostV1UserParams, opts ...ClientOption) (*PostV1UserCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV1UserID gets user by id

get user detail
*/
func (a *Client) GetV1UserID(params *GetV1UserIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1UserIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1UserIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1UserID",
		Method:             "GET",
		PathPattern:        "/v1/user/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1UserIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1UserIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetV1UserIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
PostV1User creates user

create new user
*/
func (a *Client) PostV1User(params *PostV1UserParams, opts ...ClientOption) (*PostV1UserCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostV1UserParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostV1User",
		Method:             "POST",
		PathPattern:        "/v1/user",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostV1UserReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostV1UserCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostV1UserDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
